### PR TITLE
Fix for ArgumentError issues

### LINKED ISSUE #38: ArgumentError: Invalid argument(s) for lengths
Hello! I've been using this package for a bit (have to say it's very nicely implemented!) but I ran into some issues with small page sizes (like 1 or 2). It doesn't really break the paginator, but it does raise some ArgumentError logs for me.

```
ArgumentError: Invalid argument: 1
    at throw_ (errors.dart:296:3)
    at clamp] (js_number.dart:145:7)
    at [_generateButtonList] (number_content.dart:61:40)
```

```
ArgumentError: Invalid argument(s): Length must be a non-negative integer: -4
    at wrapException (js_helper.dart:1190:19)
    at allocateGrowable (js_array.dart:96:7)
    at _generateButtonList (number_paginator-1.1.1/lib/src/ui/widgets/content/number_content.dart:64:17)
```

For the first one, I'm thinking the `numberPages` inside the `_generateButtonList` might still be getting values of 1 even though https://github.com/WieFel/number_paginator/pull/11 tries to avoid calling the function itself

For the second one, I believe `shownPages` might be getting a negative value when the pages are small or when there are no available spots somehow? The easiest solution for both might just be to return an empty array if either `numberPages <=1` or `shownPages <= 0` but I'm not sure if there are any other ideas

### PR DESCRIPTION
**Pull request by juanmanjarres**
Closes #38. This PR makes only one of the page buttons show up if there is not enough space to fit everything, and also adds some guards to return an empty list in case we hit weird values.
It also adds a fix to a warning on the web example.
Screenshot 2026-02-12 at 3 01 44 PM

### CODE REVIEW

File: lib/src/ui/widgets/content/number_content.dart [hunk 1]
```diff
@@ -32,13 +32,17 @@ class NumberContent extends StatelessWidget {
...
           builder: (context, currentPage, child) => Row(
             mainAxisAlignment: mainAxisAlignment,
-            children: [
-              _buildPageButton(context, currentPage, 0),
-              if (_frontDotsShouldShow(numberPages, currentPage, availableSpots)) _Dots(),
-              if (numberPages > 1) ..._generateButtonList(context, currentPage, availableSpots),
-              if (_backDotsShouldShow(numberPages, currentPage, availableSpots)) _Dots(),
-              if (numberPages > 1) _buildPageButton(context, currentPage, numberPages - 1),
-            ],
+            children: (availableSpots > 3)
```
Comment (WieFel) [inline lib/src/ui/widgets/content/number_content.dart]: here we should do `>= 3` or `> 2`

Current version `> 3` would leave too much empty space
Image

With `>= 3`:

Image

**Review by WieFel — CHANGES_REQUESTED** [review]
Thanks for the PR. I found this minor improvement that should be done

File: lib/src/ui/widgets/content/number_content.dart (hunk 1 above)
Comment (juanmanjarres) [reply lib/src/ui/widgets/content/number_content.dart]: sorry for the delay, just updated the PR with this change but let me know if there's anything else!

**Comment by WieFel** [comment]
@juanmanjarres your PR was merged and I released a new version `1.1.2`. Thanks for the contribution :)
